name: Clear GitHub Pages Cache

on:
  push:
    branches:
      - gh-pages

jobs:
  clear_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear GitHub Pages cache
        run: |
          echo "::group::Clearing GitHub Pages Cache"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds
          echo "::endgroup::"

      - name: Commit cache-busting update
        run: |
          echo "<!-- Cache Busted: $(date) -->" >> index.html
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add index.html
          git commit -m "Bump cache [skip ci]" || echo "No changes to commit"
          git push
